name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 0.1.1
author: Joni Katajamäki <joni.katajamaki@gmail.com>
homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  path: ^1.4.1
  source_gen: ^0.9.4
  mobx:
    git:
      url: https://github.com/lext-7/mobx.dart.git
      ref: 2ac0851035c9aa5e65d6e58d9209660a21994f5d
      path: mobx
  build: ^1.1.0
  analyzer: ^0.35.4

dev_dependencies:
  logging: ^0.11.3
  build_runner: 1.3.1
  build_test: ^0.10.5
  test_coverage: ^0.2.0
  test: ^1.0.0
  mockito: ^4.0.0
