name: flutter_mobx
description:
  Flutter integration for MobX. It provides the Observer widget that automatically rebuilds
  when the tracked observables change.
version: 0.1.1
author: Joni Katajamäki <joni.katajamaki@gmail.com>
homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  mobx:
    git:
      url: https://github.com/lext-7/mobx.dart.git
      ref: 2ac0851035c9aa5e65d6e58d9209660a21994f5d
      path: mobx
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
